version: "3.8"

networks:
  llm_network:
    name: llm_network
    driver: bridge
    external: true

services:
  datamind_ai:
    build:
      context: ./chatExcel
    environment:
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST} # Set the virtual host for Nginx to route traffic
      - GROQ_API_KEY=${GROQ_API_KEY}
    networks:
      - llm_network
    restart: always
